DROP DATABASE IF EXISTS `0voice_chatroom`;
CREATE DATABASE IF NOT EXISTS 0voice_chatroom;
USE 0voice_chatroom;
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password TEXT NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (username),
  UNIQUE (email)
);


CREATE TABLE IF NOT EXISTS room_info ( 
    room_id VARCHAR(64) NOT NULL PRIMARY KEY, 
    room_name VARCHAR(255) NOT NULL, 
    creator_id BIGINT NOT NULL, 
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    INDEX idx_creator (creator_id) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS room_member ( 
    id BIGINT PRIMARY KEY AUTO_INCREMENT, 
    room_id VARCHAR(64) NOT NULL, 
    user_id BIGINT NOT NULL, 
    is_deleted TINYINT NOT NULL DEFAULT 0, 
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    UNIQUE KEY unique_room_user (room_id, user_id), 
    INDEX idx_room_id (room_id), 
    INDEX idx_user_id (user_id) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;